version: '3'

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
  rabbit:
    container_name: rabbit
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
  es:
    container_name: elasticsearch
    image: elasticsearch:6.5.0
    ports:
      - "9200:9200"
    environment:
      - cluster.name=wcm-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
